FROM tomcat:9.0-jdk17-temurin

ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Dfile.encoding=UTF-8"

RUN rm -rf /usr/local/tomcat/webapps/*

COPY target/pet-shop-learning-1.0.0.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
